# Use root/pestillo as user/password credentials
version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - DATABASE_HOST=postgres
      - POSTGRES_USER=javier
      - POSTGRES_PASSWORD=pestillo
      - POSTGRES_DB=prison

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080